name: Redistribution
version: 0.0.1
main: net.sonorabuild.redistributionplugin.RedistributionPlugin
api-version: 1.16
commands:
  redis:
    description: Main command for 'Redistribution' plugin.
    usage: /redis