name: Redistribution
version: 0.1.1
main: net.sonorabuild.redistributionplugin.RedistributionPlugin
api-version: 1.16
commands:
  redis:
    description: Main command for the 'Redistribution' plugin.
    usage: /redis